# Generated by Django 4.2 on 2023-04-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0002_establishment_alter_establishments_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arrangement.users')),
                ('min_bill_value', models.PositiveIntegerField(null=True)),
            ],
            bases=('arrangement.users',),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arrangement.users')),
                ('max_spent_value', models.PositiveIntegerField(null=True)),
            ],
            bases=('arrangement.users',),
        ),
        migrations.RemoveField(
            model_name='arrangements',
            name='user1',
        ),
        migrations.AlterField(
            model_name='establishment',
            name='category',
            field=models.CharField(choices=[('r', 'restaurant'), ('c', 'cafe'), ('p', 'bar')], max_length=5),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='category',
            field=models.IntegerField(choices=[('r', 'restaurant'), ('c', 'cafe'), ('p', 'bar')]),
        ),
        migrations.AddField(
            model_name='arrangements',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.guest'),
        ),
        migrations.AddField(
            model_name='arrangements',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.host'),
        ),
    ]
