# Generated by Django 4.2 on 2023-04-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0003_guest_host_remove_arrangements_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishments',
            name='category',
            field=models.IntegerField(choices=[(1, 'restaurant'), (2, 'cafe'), (3, 'bar')]),
        ),
        migrations.AlterField(
            model_name='establishmentsrating',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.establishments'),
        ),
        migrations.DeleteModel(
            name='Establishment',
        ),
    ]
