# Generated by Django 4.2 on 2023-05-09 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0005_alter_establishments_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrangements',
            options={'verbose_name_plural': 'Свидания'},
        ),
        migrations.AlterModelOptions(
            name='establishments',
            options={'verbose_name_plural': 'Заведения'},
        ),
        migrations.AlterModelOptions(
            name='establishmentsrating',
            options={'verbose_name_plural': 'Рейтинг заведений'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name_plural': 'Гости'},
        ),
        migrations.AlterModelOptions(
            name='hobbies',
            options={'verbose_name_plural': 'Хобби'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name_plural': 'Приглашающие'},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name_plural': 'Паспорт'},
        ),
        migrations.AlterModelOptions(
            name='userrating',
            options={'verbose_name_plural': 'Рейтинг пользователей'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveIndex(
            model_name='establishments',
            name='arrangement_name_7ed026_idx',
        ),
        migrations.RemoveIndex(
            model_name='guest',
            name='arrangement_min_bil_fc65a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='host',
            name='arrangement_max_spe_30f636_idx',
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 5, 9, 14, 56, 52, 525572)),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(default='Minsk', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='users',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
